name: genau
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.14
  - pip:
      - aiohttp==3.8.6
      - cryptography==42.0.7
      - gensim==4.3.2
      - h5py==3.11.0
      - huggingface-hub==0.23.3
      - ipython==8.17.2
      - matplotlib==3.8.1
      - audioread==3.0.1
      - boto3==1.34.108
      - librosa==0.9.2
      - loguru==0.7.2
      - moviepy==1.0.3
      - numpy==1.23.5
      - omegaconf==2.3.0
      - pandas==2.2.2
      - pillow==10.1.0
      - pytorch-lightning==2.1.1
      - rclone==0.4.4
      - requests==2.32.3
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - six==1.16.0
      - soundfile==0.12.1
      - timm==0.4.12
      - tokenizers==0.19.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchlibrosa==0.1.0
      - torchmetrics==1.2.0
      - torchvision==0.16.2
      - tqdm==4.66.4
      - transformers==4.41.2
      - triton==2.1.0
      - wandb==0.17.1
      - wave==0.0.2
      - webdataset==0.2.86
      - wget==3.2
      - einops==0.7.0
      - regex==2024.5.15
      - ftfy==6.2.0
      - laion-clap==1.1.4
      - xformers==0.0.23
      - yt-dlp
      - huggingface_hub
      - taming-transformers-rom1504==0.0.6
